- src/RFC-0312_DANHighLevelSpecification.md
Description
---
We have started to call the "owner" of the asset the CC or ConstitutionCommittee.  This is the person(s) who is allowed to change the Constitution  UTXO and is in all effect the owner of the asset. The update to the RFC adds in the CC and describes their role and fixes places where it's still mentioned as VNC. 
This also removes the initial reward scheme as we decided to remove as it contains many vulnerabilities to gain it, that is against the good principles for asset management.
> Add mention of the CC

- src/RFC-0306_DANTemplateRegistration.md
- src/SUMMARY.md
Description
----
Adds the template registration UTXO RFC
----
Details how DAN templates could be registered on the base layer.
> docs: template registration UTXO

- src/RFC-0140_Syncing_and_seeding.md
- src/SUMMARY.md
Rename the title of this RFC so that it is easier to find pruned mode details.
There isn't a dedicated "pruned mode" RFC, and in some places we want to reference it. I had to find this by using the search, so this is an attempt to make it easier to find by the Summary tree
> fix(rfc140): rename title for clarity

- src/RFC-0201_TariScript.md
Although cut-through prevention is mentioned early in the document, the reasoning was included in the explanation, which was very far down the document. I've moved the explanation earlier, but kept the implementation details where they were.
> fix(rfc201): move cut through explanation earlier

- src/RFC-0202_TariScriptOpcodes.md
Description
---
- Adds docs for CheckMultiSig(Msg) and CheckMultiSigVerify(Msg)
- Update error table to reflect implementation
---
Reconcile implementation and RFC differences
> fix(202-tariscript): add missing OP_CHECKMULTISIG/VERIFY and update error codes

- src/RFC-0201_TariScript.md
- src/RFC-0202_TariScriptOpcodes.md
Description
---
Added aggregate metadata and script signatures to the transaction output and input (RFC-0201) and multi-sig opcodes (RFC-0202).
---
This is handy for multiple parties (`m-of-n`) to create outputs and spend outputs. 
To create a multi-party output `n-of-n` receiver parties need to:
- agree on the `m-of-n` TariScript script out of band;
- create an aggregated receiver portion of the metadata signature if the spending key is sharded. 
To spend an `m-of-n` input, `m` parties need to agree on the `m-of-n` TariScript input out of band and create an aggregated script signature.
_**Main additions to RFC-0201 text is shown below**_
---
---
---
`mdbook serve` renders fine
> feat: add aggregate signatures to transaction inputs and outputs

- src/RFC-0202_TariScriptOpcodes.md
- src/RFC-0230_HTLC.md
Description
---
Originally I deprecated this RFC in favour of moving the content into the TariScript opcodes examples section. The two examples are similar but hidden in the details of the opcodes example is that it's a multiparty transaction where the one in the 0230 example is not. So I've left the RFC separated as it more closely matches the implementation and atomic swap use case.
Updated the naming in the opcode rfc just for disambiguation purposes.
---
Stabilising 
---
> fix(htlc stabilising): update htlc rfcs

- src/RFC-0250_Covenants.md
Description
---
Updates include:
- Correcting opcodes on CovenentArg, Output field tags, operations, and filters
- Removing the NFT example referencing a deprecated RFC
- Updated naming and examples of removed/renamed filters and operations
---
Prep'n for wen moon.
---
Compared it to the code a bit.
> docs: rfc-0250 covenants stabilized

- src/RFC-0152_EmojiId.md
Description
---
Updates the emoji ID encoding and decoding algorithms in [RFC-0152](https://rfc.tari.com/RFC-0152_EmojiId.html) for clarity. Makes other miscellaneous changes for a smoother read.
Closes [issue 61](https://github.com/tari-project/rfcs/issues/61).
---
The recent [PR 48](https://github.com/tari-project/rfcs/pull/48) updates the emoji ID RFC-0152 to include checksum masking, which enables the use of network identifiers. This work updates the encoding and decoding algorithm descriptions for clarity. It also makes other assorted changes for grammar and readability.
---
Built locally and examined to ensure nothing exploded.
> docs: update emoji ID RFC-0152 algorithms

- src/Glossary.md
- src/RFC-0120_Consensus.md
Description
---
This moved RFC_0120 to stable. 
Sort maintainers list by alphabetical order.
> docs: move RFC_0120 to stable

- README.md
- src/Glossary.md
- src/RFC-0201_TariScript.md
Description
---
Updates the [glossary](https://rfc.tari.com/Glossary.html) to add an entry for commitment and public key signatures, and references this entry in [RFC-0201](https://rfc.tari.com/RFC-0201_TariScript.html). Also updates the [`readme`](https://github.com/tari-project/rfcs/blob/main/README.md) for improved clarity on building and serving the `mdbook` locally.
---
A [recent PR](https://github.com/tari-project/rfcs/pull/54) updates RFC-0201 to reference commitment and public key signatures via links to [an implementation PR](https://github.com/tari-project/tari-crypto/pull/131). This work moves the description of these signatures to the glossary.
Also updates the `readme` to provide better clarity and specificity on how to build and serve the RFC `mdbook` …
> docs: add a glossary entry for commitment and public key signatures

- src/RFC-0313_VNRegistration.md
Description
---
- uses consistent notation
- changes ordering to be by shard key
- clarifies the start/end of the validity of the VN registration 
---
Issue #73, #75, #76
> fix: updates to RFC-0313

- src/RFC-0120_Consensus.md
- src/RFC-0131_Mining.md
- src/RFCD-0121_ConsensusEncoding.md
- src/SUMMARY.md
Description
---
Moved old RFC-0121 describing Consensus Encoding to the deprecated section.
---
Initial implementation is deprecated in favor of `borsh`
---
> fix: rfc-0121 is deprecated

- src/RFC-0172_PeerToPeerMessagingProtocol.md
Description
---
Clarifies empty body rules for EnvelopeBody
---
In the encrypted case, a valid node should discard a message if the encoded `EnvelopeBody` is zero-sized. A cleartext `EnvelopeBody` may be zero-sized as this is valid proto3 encoding.
Ref https://github.com/tari-project/tari/pull/5130
> fix(rfc-0172): clarify empty body rules for EnvelopeBody

- src/RFC-0182_CommitmentSignatures.md
- src/RFC-0201_TariScript.md
- src/SUMMARY.md
Description
---
Moves the description of commitment and public key (CAPK) signatures from RFC-0201 to a new RFC-0182. Adds a variation for commitments with revealed value. Includes new security proofs for both constructions.
---
There has been discussion about ways to make transactions more efficient in the case where the sender does not wish to hide a commitment's value. It turns out that CAPK signatures can be modified such a verifier can assert a commitment binds to a revealed value, which removes the need for range proof verification.
This PR does a few things. First, it moves the existing CAPK signature description from RFC-0201 to its own new RFC-0182. Then, it splits the description into two protocols: one that hides the commitment value, and another that …
> feat: updated CAPK signature and security proofs

- src/RFC-0154_DeepLinksConvencion.md
Description
---
Replaces mention of public key with Tari address as the wallets don't use raw public keys anymore.
> fix: replace public key with tari address

- src/RFC-0154_DeepLinksConvencion.md
- Added /contacts and /profile deep links descriptions to the RFC-0154
> feat: rfc-0154 contacts and profile deep links

- src/RFC-0182_CommitmentSignatures.md
Description
---
Adds proving system relations to [RFC-0182](https://rfc.tari.com/RFC-0182_CommitmentSignatures.html).
---
The recent addition of RFC-0182 includes details for commitment and public key signatures. These include interactive protocols, descriptions of the use of the Fiat-Shamir technique for non-interactivity, and security proofs. However, the RFC did not specifically list the proving system relations used for the two protocols, instead describing them more informally in the introduction.
This PR adds the proving system relations for improved clarity.
---
The changes build and appear to render correctly.
> feat: add proving system relations

- src/RFC-0120_Consensus.md
Description
---
Current implementation of the coinbase builder makes these 0, but we do not have a rule that specifies they have to be 0. 
---
If they are not zero, you cannot do validation on the coinbase kernel. 
The script_offset makes zero difference on the malleability of the kernel so its not required. There is also no spending script key, meaning you leak the private key to sender_offset key. 
The transactions offset makes it impossible to test the value of the kernel in any block that has more than the coinbase transaction.
> fix: coin base rules

- src/RFC-0181_BulletproofsPlus.md
Description
---
Adds details of a Bulletproofs+ optimization to RFC-0181. Removes old benchmark data.
---
The [Bulletproofs+ implementation](https://github.com/tari-project/bulletproofs-plus) contains a particular optimization used when [computing](https://github.com/tari-project/bulletproofs-plus/blob/d495fb24f9c7c34e0bfb0a38598b67e216fc56bf/src/range_proof.rs#L616-L625) a vector sum. This optimization is not particularly obvious, as it uses some fun arithmetic and a fact about [geometric series partial sums](https://mathworld.wolfram.com/GeometricSeries.html).
This PR adds details about the math behind the optimization to [RFC-0181](https://rfc.tari.com/RFC-0181_BulletproofsPlus.html). It also removes outdated benchmark data, similarly to earlier …
> feat: range proof sum optimization and cleanup

- src/RFC-0181_BulletproofsPlus.md
Description
---
Updates range proof [RFC-0181](https://rfc.tari.com/RFC-0181_BulletproofsPlus.html) to add comparative performance data and improve notation.
Closes #102.
---
An [earlier PR](https://github.com/tari-project/rfcs/pull/101) removed outdated benchmark data, but it was [suggested](https://github.com/tari-project/rfcs/pull/101#issuecomment-1646739122) to include reasonable comparative performance data against Bulletproofs. This data has been added for both proof size and verification complexity.
Some notation was incomplete or incorrect. In particular, sum and index bounds were left implicit in many places, and indexing relating to mask recovery was incorrect. Both of these have been addressed.
---
The changes build and appear to …
> feat: range proof performance and notation fixes

- src/RFC-0181_BulletproofsPlus.md
Description
---
Adds a brief note about range proof proving efficiency. Adds rough benchmarks against Bulletproofs.
---
It was [suggested](https://github.com/tari-project/rfcs/pull/103#issuecomment-1663380301) to add information about proving efficiency to range proof [RFC-0181](https://rfc.tari.com/RFC-0181_BulletproofsPlus.html).
Quantifying proving efficiency is more subtle than verification efficiency, since proof generation doesn't reduce to a multiscalar multiplication operation and requires a variable number of rounds. Instead of bogging down the RFC with a long list of group element operation counts, this PR adds a more general note.
Informal benchmark comparing the [Tari implementation](https://github.com/tari-project/bulletproofs-plus) to the …
> feat: range proof proving efficiency

- src/RFC-0120_Consensus.md
Description
---
Adds a rule to RandomX headers to stop RandomX headers from being malleable. 
Changes Sha -> Sha3x
Monero -> RandomX
> fix: malleable monero headers

- src/RFC-0303_DanOverview.md
- src/RFC-0310_SubmarineSwaps.md
- src/RFC-0320_TurbineModel.md
Description
---
The whimsical and Discworld-related placeholder name for DAN tokens was `Thaum`. This has since been renamed to Tari. (And L1 tokens are now Minotari).
> chore: rename thaum to tari

- src/RFC-0141_Sparse_Merkle_Trees.md
- src/SUMMARY.md
This Request for Comment (RFC) proposes replacing the current Mutable Merkle Mountain Range (MMMR) data structure 
used for tracking the commitment to the UTXO set, with a Sparse Merkle tree (SMT).
A sparse Merkle tree ([SMT]) is a Merkle-type structure, except the contained data is indexed, and each datapoint is 
placed at the leaf that corresponds to that datapoint’s index. Empty nodes are represented by a predefined "null" value.
Since every empty node has the same hash, and the tree is sparse, it is possible to prune the tree in a way such 
that only the non-zero leaf nodes and placeholders marking the empty sub-trees are stored. Therefore, SMTs are 
relatively compact.
> docs: sparse merkle trees

- src/RFC-0140_Syncing_and_seeding.md
Description
---
Change prune of outputs to should
---
The pruning of outputs is not consensus critical, if the node does not prune it at that height, and only later it only effects the base node storage and not consensus.
> feat: update RFC-0140 to reflect current usage

- src/RFC-0305_Consensus.md
- src/RFC-0330_Cerberus.md
- src/SUMMARY.md
RFC-304 was already taken. Renaming to RFC-305.
We use P-cerb, not O-Cerb.
Other editorial changes.
> chore: edits and numbering fix

- src/RFC-0202_TariScriptOpcodes.md
Description
---
Updates the documentation for the `ToRistrettoPoint` opcode.
---
This opcode now requires a canonical scalar parsing. Further, the existing documentation was somewhat unclear. This PR updates the documentation for clarity and correctness.
---
It renders as expected.
> docs: update documentation for `ToRistrettoPoint` opcode

- book.toml
- src/RFC-0385_StableCoins.md
- src/SUMMARY.md
- src/assets/tether.sol
- src/assets/usdc.sol
This Request for Comment (RFC) describes a possible manifestation of a privacy-preserving stablecoin on the Tari Digital Assets Network (DAN).
The stablecoin design broadly follows that of Tether and Circle's ERC-20 stabecoin, with the exception that amounts and transacting parties are confidential.
The latest draft represents a more fully-fledged design for a privacy-enabled stablecoin and one that approaches feasibility.
It is still likely insecure in places and there are still a few holes to plug in some of the operations, but the broad brushstrokes are certainly there.
The specification given here focuses on a surveillance-enabled stablecoin (i.e. CBDC) model. 
The specification is presented neutrally as pure technology and should not be construed as an endorsement of centralised …
> feat: stablecoin draft specification

- src/RFC-0385_StableCoins.md
- src/SUMMARY.md
The title was wrong and inconsistent in the ToC
> fix: stablecoin rfc title

- src/RFC-0385_StableCoins.md
Description
---
Corrects typos and makes small updates to stablecoin RFC-0385.
Supersedes #117.
---
Stablecoin RFC-0385 had several typos, as well as outdated content from previous design iterations. This PR makes the necessary fixes.
---
The RFC builds and renders correctly.
> fix: typos and small fixes

- .github/workflows/rfc_deploy.yml
Locally, mermaid works fine on v0.4.34. The workflow still has 0.4.10, so I'm assuming upgrading will fix the mermaid not displaying properly issue.
> fix: upgrade mdbook

- src/RFC-0174_Chat_Metadata.md
- src/SUMMARY.md
Description
---
This rfc's purpose is to standardize the data format for metadata consistency across clients who want to share common functionality.
---
The more compatibility the more better
> docs(chat): rfc chat metadata proposal

- src/RFC-0205_HardwareTransactions.md
- src/RFC-0205_LedgerTransactions.md
- src/SUMMARY.md
Description
---
Intial draft for hardware wallet transactions. 
---
---
> feat: hardware wallet transactions

- .gitignore
- build.js
- mdbook.env
- package-lock.json
- package.json
Add a node.js-based build script so that this site can run in Cloudflare pages.
The script does the following:
1. Downloads the specified version of mdbook from the GitHub releases page
2. Verifies its SHA256 hash
3. Extracts it to a temporary directory
4. Runs mdbook build against the book.toml file in the current directory
5. Places the built book in the temporary directory
`mdbook.env` (which is checked in and MUST NOT hold any secrets) allows you to set the version of mdbook and its hash.
> feat: node-based build script

- build.js
- package-lock.json
- package.json
dotenv was used for testing of the `build.js` script and is not needed anymore.
Removing it for security reasons. 
There weren't any major concerns but some fat-finger errors may have led to deployment problems. The envars are set in the build environments (e.g. cloudflare) or have sane fallback defaults.
> fix: remove dotenv

- src/RFC-0201_TariScript.md
Description
---
This PR doesn't not remove an unintended double negative.
---
The presence of the double negative doesn't not change the description of scripting support across the ecosystem.
---
The page renders not incorrectly, and doesn't not fail not to build.
> chore: remove unintentional double negative

- src/RFC-0154_DeepLinksConvencion.md
- Updated documentation for deep links that uses Tari address. Now keys used to store address value are named `tariAddress`.
> feat: improve RFC-0154 - Update

- src/RFC-0001_overview.md
- src/RFC-0131_Mining.md
Description
---
Corrected references in RFC 001 and RFC-0131 to reflect accurate split in terms of merge mining and hybrid mining stated percentages.
---
RFCs were still referencing a 60/40 split, which is inaccurate.
> fix: updated merge/hybrid mining percentages to reflect 50/50 split

- src/RFC-0155_TariAddress.md
> feat: add payment id to tari address.
