tari-project/rfcs

src/RFC-0120_Consensus.md

Description
---
Updates the output hash to match the current output hash in code

fix: update rfc 0120 to reflect code

---

src/RFC_template.md

Adds a change log heading to the RFC template

feat: update template

---

src/RFC-0152_EmojiId.md

Description
---
[RFC-0152](https://rfc.tari.com/RFC-0152_EmojiId.html), which defines emoji IDs, is outdated. This brings it up to date and includes changes from [PR 4639](https://github.com/tari-project/tari/pull/4639), which updates the checksum algorithm.
---
The following are outdated in RFC-0152:
- Versioning is not used in the codebase.
- The emoji character set in the codebase contains only 256 symbols.
- The encoding method in the RFC is not used in the codebase.
Further, it is likely that the checksum algorithm will change with PR 4639.

docs: update emoji ID

---

src/RFC_0388_BearerTokens.md

An RFC for DAN layer bearer tokens

feat: add rfc for bearer tokens

---

src/RFC-0312_DANHighLevelSpecification.md

Description
---
This updates the contract abandonment process to the current to-be-implemented code.

Abandonment proposal

---

src/Glossary.md
src/RFC-0190_Mempool.md

Description
---
The current mempool RFC is outdated as to how the current mempool implementation is. 
This is an update to bring the RFC in line with the implementation.

docs: update mempool

---

src/RFC-0203_StealthAddresses.md

Description
---
This pull request updates the one-time (stealth) address [RFC-0203](https://rfc.tari.com/RFC-0203_StealthAddresses.html) to replace its dual-key design with the single-key design currently supported by the codebase.
---
The current version of RFC-0203 describes the CryptoNote/Monero-style dual-key design for one-time addresses, which is useful for separating scanning capabilities from spend authority. However, the codebase supports only a single-key design. This work updates RFC-0203 to be consistent with the current implementation.
---
This PR was tested by serving the `mdbook` and inspecting the resulting page for correctness.

docs: update stealth address RFC-0203 for single keys

---

src/RFC-0120_Consensus.md
src/RFC-0122_Burning.md

Description
---
This will us to do burns on UTXOs. 
---
Many second layer functionality requires the burning of main chain coins. This will enable Tari to be burned and be removed from the emission.

feat: rfc for burning

---

src/RFC-0201_TariScript.md

* Removed refernce to clacks
* Updated Mimblewimble link

fix(rfc201): removed clacks

---

src/RFC-0123_One_sided_replay_attacks.md

Discussion about what to do with the possible one-sided transaction replay attack.

Discussion replay attack 1-sided tx

---

src/RFC-0201_TariScript.md

Hopefully clarifies the high level process a bit more

fix(rfc201): clarify high level process of TariScript

---

src/RFC-0131_Mining.md

Updates the mining RFC to how the current code and consensus code is.

docs: update mining rfc

---

src/RFC-0131_Mining.md

Description
---
Add change log to RFC 0131

docs: add change log to RFC 0131

---

src/RFC-0203_StealthAddresses.md

Description
---
Stabilizes RFC 203, testing status, adds changelog
---
Verified the stealth address implementation and RFC correspond.

fix(rfc/203): stealth addresses, add changelog and testing badge

---

src/RFC-0171_MessageSerialisation.md

Description
---
- mention protobuf as the chosen wire format
- remove references to zeroMQ
- include bincode as a used binary format
- set to active

fix(rfc-171): update to include protobuf

---

src/RFC-0240_AtomicSwap.md

Description
---
Add change log to RFC-0240

docs: rfc_240 add change log

---

src/RFC-0132_Merge_Mining_Monero.md

Description
---
Update the rfc 132 - merge mining rfc, some fields were outdated.

fix: update fields of 132

---

src/RFC-0171_MessageSerialisation.md

Description
---
"Active" is not a valid status. Change to "stable", and add same to Change Log

feat: stabilise rfc-0171

---

src/RFC-0203_StealthAddresses.md

Description
---
* Stabilise RFC-203
* Add change log entry
* Minor cosmetic edits

feat: stabilise rfc-0203

---

src/RFC-0131_Mining.md

Description
---
* A few small edits - content is materially unchanged.
* Add change log entry
* Change status to STABLE

feat: stabilise rfc-0131

---

src/RFC-0173_Versioning.md

Description
---
* Stabilises RFC-0173
* Minor edits - content is materially unchanged
* Change log added

feat: stabilise rfc-0173

---

src/RFC-0140_Syncing_and_seeding.md

Description
---
For the most part the RFC was pretty much aligned with the code. The only changes:
* Updated and expanded the `chain_metadata` fields.
* Minor fixes: document status, year and some minor grammar errors.
---
RFC-0140 must align with the actual code
---
mdbook serve

docs: update rfc-0140

---

src/Glossary.md
src/RFC-0110_BaseNodes.md

Description
---
Added a little extra info regarding pruned nodes and peer validation.
Moved RFC to stable.
---
Gett'n things updated.

fix(stable base nodes): minor updates and move to stable

---

src/RFC-0172_PeerToPeerMessagingProtocol.md

This is a huge RFC.
I've updated parts of it, but it is still very out of date

docs: update rfc172

---

src/RFC-0201_TariScript.md
src/RFC-0204_TariScriptExamples.md
src/SUMMARY.md

docs: update rfc0201-tariscript

---

src/RFC-0152_EmojiId.md

Description
---
Adds in a few extra small improvements for RFC-0152
See #https://github.com/tari-project/rfcs/pull/48#pullrequestreview-1177403852

docs: rfc-0152 small improvements

---

src/RFC-0310_SubmarineSwaps.md
src/RFC-03XX_SubmarineSwaps.md

Discussion of how submarine swaps can work the second layer

Submarine swaps

---

src/RFC-0314-VNCSelection.md

Description
---
1st draft of the VNC selection RFC

docs: vnc selection

---

src/RFC-0110_BaseNodes.md
src/RFC-0230_HTLC.md

Description
---
Minor updates to updates.
---
Make it a lil more accurate.

docs: extend the changelog info

---

src/RFC-0140_Syncing_and_seeding.md

Description
---
Added a changelog section to the RFC, reflecting the total history
---
This RFC must have a changelog
---
mdbook serve

docs: add changelog to rfc-0140

---

src/RFC-0160_BlockSerialization.md

Description
---
Updated RFC-0202 for code review/audit by bringing it in line with the actual code.
---
See above
---
`mdbook serve`

docs: update rfc_0160 for code review/audit

---

src/RFC-0313_VNRegistration.md

Description
---
- replace rust code with plain-language pseudocode
- update database indexes to reflect the implementation
- fix/remove a few broken links

docs(RFC-0313): minor updates to reflect implementation

---

src/RFC-0150_Wallets.md

Description
---
Added table of contents, recovery process overview and other minor changes
---
Iterative review of existing RFCs.
---

docs: minor changes for RFC-0150/Wallets

---

src/RFC-0153_StagedWalletSecurity.md

Description
---
Typo in Money formatting and stage numbering fixed.

fix: typo in rfc-0153

---

src/RFC-0172_PeerToPeerMessagingProtocol.md

Description
---
Implementation parity updates to RFC-0172
---
Stabilise RFC-0172

docs: stablise rfc-0172-p2p-messaging 

---

src/Glossary.md
src/RFC-0120_Consensus.md

Description
---
Add description of coinbase extra as well as what it can be used for.

feat: add coinbase extra

---

src/RFC-0204_TariScriptExamples.md

Description
---
Added latex `newcommand` to fix rendering of math

fix: rfc 204 rendering

---

src/RFC-0201_TariScript.md

Description
---
Fixes some spelling and grammar mistakes

fix: grammer and spelling

---

src/RFC-0305_DanTimeManagement.md

Description
---
This is a 1st draft of ideas surrounding vn epoch/time management

docs: epoch/time management

---

.github/workflows/pr_title.yml

Description
Update pr_title workflow.
Prevent code injection.

ci(fix): prevent code injection

---

src/RFC-0111_BaseNodeArchitecture.md
src/RFC-0131_Mining.md
src/RFC-0140_Syncing_and_seeding.md
src/RFC-0150_Wallets.md
src/RFC-0153_StagedWalletSecurity.md
src/RFC-0160_BlockSerialization.md
src/RFC-0170_NetworkCommunicationProtocol.md
src/RFC-0172_PeerToPeerMessagingProtocol.md
src/RFC-0173_Versioning.md
src/RFC-0190_Mempool.md
src/RFC-0201_TariScript.md
src/RFC-0203_StealthAddresses.md
src/RFC-0230_HTLC.md
src/RFC-8003_TariUseCases.md
src/RFCD-0010_CodeStructure.md
src/RFCD-0130_Mining.md
src/RFCD-0300_DAN.md
src/RFCD-0302_ValidatorNodes.md
src/RFCD-0304_VNCommittees.md
src/RFCD-0341_AssetRegistration.md
src/RFCD-0360_NFTInvoices.md

Remove/replace anyone marked as a maintainer that is no longer maintaining RFCs.

fix: remove old maintainers

---

.github/workflows/rfc_deploy.yml

Upgrade mdbook

---

.github/workflows/rfc_deploy.yml

fix: upgrade mdbook-mermaid

---

.github/workflows/rfc_deploy.yml
.github/workflows/rfc_test.yml
book.toml

GA can't find the preprocessor binary for some reason.
Description
---
---
---

fix: fix mermaid again

---

src/RFC-0331_Indexers.md

RFC-331 was just a stub. This provides the content for it.

feat: update content for rfc-331

---

.github/workflows/rfc_deploy.yml
.github/workflows/rfc_test.yml
book.toml
src/RFC-0350_TariVM.md
src/RFC_template.md
src/SUMMARY.md

A rough draft of the Tari network logic layer description.
The logic layer has many moving parts and I'm trying to thread the needle of making it a useful roadmap for the code without simply rewriting the code in English, or being too vague as to make it useless.
It will definitely need another pass or two.

feat: tari logic layer
